# Model configuration
model_name: eva02_base            # Model class name
# load_name: "./output/threshold_resnet18.pth"
# load_name: "./output/threshold_resnet18_neuron.pth"
load_name: "./output/threshold_eva_base_999.pth"
# load_name: "./output/threshold_resnet18_channel_999.pth"
# load_name: "./output/threshold_resnet18_channel.pth"

# load_name: "./output/threshold_resnet18_neuron_999.pth"
# load_name: "./output/threshold_resnet18_999.pth"

# load_name: "checkpoint.pth"
# model_name: resnet34            # Model class name
# load_name: "../models/qe-conversion/resnet34/resnet34_imagenet.pth"
# model_name: vgg16_bn
# load_name: "../models/qe-conversion/vgg16/vgg16_bn_imagenet.pth"

# mode: test_ann
mode: test_snn                  # Operation mode: test_ann, get_threshold, test_snn, train_snn
sop: True
save_name: ./output/xxx      # Name for saving the model

# Threshold configuration
# threshold_mode: "99.9%"         # Threshold mode for SNN neurons
# threshold_mode: "var"         # Threshold mode for SNN neurons
# threshold_level: "neuron"
# threshold_level: "channel"
threshold_level: "layer"
fx: False

# Neuron configuration
# neuron_name: MTH_diff        # Neuron model: IF, IF_with_neg, LIF, MTH
neuron_name: MTH_with_neg_line        # Neuron model: IF, IF_with_neg, LIF, MTH
num_thresholds : 8
step_mode: 'm'
# coding_type: diff_rate               # Coding type: rate or leaky_rate or diff
coding_type: rate               # Coding type: rate or leaky_rate or diff
fuse: False

# Task configuration
task: classification            # Task type: classification or others

# Dataset configuration
dataset: imagenet               # Dataset name
dataset_path: "../data"         # Path to the dataset
batchsize: 4                  # Batch size for training or testing

# Device configuration
device: "0"                     # CUDA device ID (e.g., 0 for single GPU)
distributed: false              # Enable distributed training (true or false)

# Logger configuration
logger: false                    # Enable logging
logger_path: "logs/log.txt"     # Path to save logs

# Training and Testing configuration
seed: 2024                      # Random seed for reproducibility
time: 16                         # SNN simulation time (0 for default behavior)
